
/** ----------------------------------------------------------------------------------------------------
* 
*	This code was automatically generated by the UFT Developer Application Model code generator.
*
*	Changes to this file may cause incorrect behavior and will be lost 
*	when the code is regenerated.
*
*   ----------------------------------------------------------------------------------------------------
*/
package com.aos.automation;

import com.hp.lft.sdk.*;

// This class is automatically generated by the UFT Developer Application Model code generator
public class AOSModels extends AppModelBase {	
	public AOSModels(TestObject contextTestObject) throws GeneralLeanFtException
	{
		setName("AOSModels");
		rebuildDescriptions();
	}	
}
